version: '3'

volumes:
  influxdb-storage:
  grafana-storage:

networks:
  tig:

services:
    influxdb:
        container_name: tig-influxdb
        image: influxdb
        privileged: false
        ports:
            - "8086:8086"
        volumes:
            - influxdb-storage:/var/lib/influxdb
        environment:
            - INFLUXDB_DB=${INFLUX_DB}
            - INFLUXDB_ADMIN_ENABLED=${INFLUX_ADMIN}
            - INFLUXDB_HTTP_AUTH_ENABLED=${INFLUX_HTTP_AUTH}
            - INFLUXDB_ADMIN_USER=${INFLUX_USERNAME} 
            - INFLUXDB_ADMIN_PASSWORD=${INFLUX_PASSWORD}
        networks:
          tig: 
            aliases:
              - influxdb

    grafana:
        container_name: tig-grafana
        image: grafana/grafana
        privileged: false
        ports:
            - '3000:3000'
        volumes:
            - grafana-storage:/var/lib/grafana
        networks:
          tig: 
            aliases:
              - grafana

    telegraf:
        container_name: tig-telegraf
        image: telegraf
        privileged: false
        restart: always
        ports:
          - '8080:8080'
          - '8081:8081'
        volumes:
            - ./conf/telegraf.conf:/etc/telegraf/telegraf.conf
        networks:
          tig: 
           aliases:
              - telegraf